# Generated by Django 5.2.3 on 2025-06-19 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('path', models.TextField()),
                ('duration', models.FloatField()),
            ],
        ),
    ]
