# Generated by Django 5.2.3 on 2025-06-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_video_comment_count_video_like_count_video_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='engagement_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='video',
            name='total_watch_time',
            field=models.FloatField(default=0.0),
        ),
    ]
