# Generated by Django 5.2.3 on 2025-06-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_video_engagement_data_video_total_watch_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='engagement_event_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='play_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
